{eloquent}: use lttng-tools for python3-lttng
* fixes:
  ERROR: Nothing RPROVIDES 'UNRESOLVED-python3-lttng' (but /jenkins/mjansa/build-ros-thud-mcf-herb/meta-ros/meta-ros2-eloquent/recipes-ros2/ros2-tracing/tracetools-trace_0.2.10-1.bb RDEPENDS on or otherwise requires it)
  NOTE: Runtime target 'UNRESOLVED-python3-lttng' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['UNRESOLVED-python3-lttng']
  Missing or unbuildable dependency chain was: ['ros2trace', 'tracetools-trace', 'UNRESOLVED-python3-lttng']
  Missing or unbuildable dependency chain was: ['ros2trace-dev', 'tracetools-trace', 'UNRESOLVED-python3-lttng']
  Missing or unbuildable dependency chain was: ['tracetools-trace', 'UNRESOLVED-python3-lttng']

* to provide the bindings we also need lttng-tools bbappend
  enabling python PACKAGECONFIG