{melodic} ros-distro.inc: add mapping for linux-kernel-headers
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-linux-kernel-headers' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/ros-canopen/socketcan-interface_0.8.2-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'cob-bms-driver' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-bms-driver', 'socketcan-interface', 'UNRESOLVED-linux-kernel-headers']
NOTE: Runtime target 'socketcan-bridge' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['socketcan-bridge', 'socketcan-interface', 'UNRESOLVED-linux-kernel-headers']
NOTE: Runtime target 'ainstein-radar-drivers' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ainstein-radar-drivers', 'socketcan-bridge', 'socketcan-interface', 'UNRESOLVED-linux-kernel-headers']
NOTE: Runtime target 'ainstein-radar' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ainstein-radar', 'ainstein-radar-drivers', 'socketcan-bridge', 'socketcan-interface', 'UNRESOLVED-linux-kernel-headers']
NOTE: Runtime target 'prbt-hardware-support' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['prbt-hardware-support', 'canopen-chain-node', 'canopen-master', 'socketcan-interface', 'UNRESOLVED-linux-kernel-headers']
NOTE: Runtime target 'canopen-chain-node' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['canopen-chain-node', 'canopen-master', 'socketcan-interface', 'UNRESOLVED-linux-kernel-headers']
NOTE: Runtime target 'cob-elmo-homing' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-elmo-homing', 'canopen-402', 'canopen-master', 'socketcan-interface', 'UNRESOLVED-linux-kernel-headers']
NOTE: Runtime target 'canopen-402' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['canopen-402', 'canopen-master', 'socketcan-interface', 'UNRESOLVED-linux-kernel-headers']
NOTE: Runtime target 'canopen-master' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['canopen-master', 'socketcan-interface', 'UNRESOLVED-linux-kernel-headers']
NOTE: Runtime target 'socketcan-interface' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['socketcan-interface', 'UNRESOLVED-linux-kernel-headers']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>