{melodic} ros-distro.inc: add mapping for various gstreamer1.0 packages
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-gstreamer1.0' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-play_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-capture_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/sound-play_0.3.3.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'audio-play' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['audio-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'audio-common' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['audio-common', 'audio-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'audio-capture' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['audio-capture', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'ros-speech-recognition' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-speech-recognition', 'audio-capture', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'julius-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['julius-ros', 'audio-capture', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'jsk-3rdparty' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['jsk-3rdparty', 'julius-ros', 'audio-capture', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'sound-play' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['sound-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'pr2eus' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pr2eus', 'sound-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'jsk-pr2eus' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['jsk-pr2eus', 'pr2eus', 'sound-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'pr2eus-tutorials' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pr2eus-tutorials', 'pr2eus', 'sound-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'pr2eus-moveit' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pr2eus-moveit', 'pr2eus', 'sound-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'jsk-topic-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['jsk-topic-tools', 'sound-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'jsk-tools' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['jsk-tools', 'jsk-topic-tools', 'sound-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'jsk-common' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['jsk-common', 'jsk-tools', 'jsk-topic-tools', 'sound-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'jsk-data' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['jsk-data', 'jsk-topic-tools', 'sound-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'jsk-pcl-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['jsk-pcl-ros', 'jsk-data', 'jsk-topic-tools', 'sound-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'jsk-recognition' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['jsk-recognition', 'jsk-pcl-ros', 'jsk-data', 'jsk-topic-tools', 'sound-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'jsk-perception' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['jsk-perception', 'jsk-data', 'jsk-topic-tools', 'sound-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'jsk-pcl-ros-utils' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['jsk-pcl-ros-utils', 'jsk-data', 'jsk-topic-tools', 'sound-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'imagesift' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['imagesift', 'jsk-topic-tools', 'sound-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'jsk-interactive-marker' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['jsk-interactive-marker', 'jsk-topic-tools', 'sound-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'jsk-interactive' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['jsk-interactive', 'jsk-interactive-marker', 'jsk-topic-tools', 'sound-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'jsk-visualization' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['jsk-visualization', 'jsk-interactive', 'jsk-interactive-marker', 'jsk-topic-tools', 'sound-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'jsk-interactive-test' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['jsk-interactive-test', 'jsk-interactive', 'jsk-interactive-marker', 'jsk-topic-tools', 'sound-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'resized-image-transport' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['resized-image-transport', 'jsk-topic-tools', 'sound-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'jsk-rviz-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['jsk-rviz-plugins', 'jsk-topic-tools', 'sound-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'cis-camera' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cis-camera', 'jsk-rviz-plugins', 'jsk-topic-tools', 'sound-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'tts' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['tts', 'sound-play', 'UNRESOLVED-gstreamer1.0']
NOTE: Runtime target 'voice-text' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['voice-text', 'sound-play', 'UNRESOLVED-gstreamer1.0']
ERROR: Nothing PROVIDES 'UNRESOLVED-libgstreamer-plugins-base1.0-dev' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-play_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-capture_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/gscam/gscam_1.0.1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'gscam' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gscam', 'UNRESOLVED-libgstreamer-plugins-base1.0-dev']
ERROR: Nothing PROVIDES 'UNRESOLVED-libgstreamer1.0-dev' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-play_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-capture_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/gscam/gscam_1.0.1.bb DEPENDS on or otherwise requires it)
ERROR: Nothing PROVIDES 'UNRESOLVED-gstreamer1.0-plugins-good' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-play_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-capture_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/sound-play_0.3.3.bb DEPENDS on or otherwise requires it). Close matches:
  gstreamer1.0-plugins-good
  gstreamer1.0-plugins-bad
  gstreamer1.0-plugins-ugly
ERROR: Nothing PROVIDES 'UNRESOLVED-gstreamer1.0-plugins-base' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-play_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-capture_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/sound-play_0.3.3.bb DEPENDS on or otherwise requires it). Close matches:
  gstreamer1.0-plugins-base
  gstreamer1.0-plugins-bad
ERROR: Nothing PROVIDES 'UNRESOLVED-gstreamer1.0-plugins-ugly' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-play_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-capture_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/sound-play_0.3.3.bb DEPENDS on or otherwise requires it). Close matches:
  gstreamer1.0-plugins-ugly
  gstreamer1.0-plugins-good
  gstreamer1.0-plugins-bad
ERROR: Nothing RPROVIDES 'UNRESOLVED-gstreamer1.0' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-play_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-capture_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/sound-play_0.3.3.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-gstreamer1.0' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-gstreamer1.0']
ERROR: Nothing RPROVIDES 'UNRESOLVED-gstreamer1.0-plugins-good' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-play_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-capture_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/sound-play_0.3.3.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-gstreamer1.0-plugins-good' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-gstreamer1.0-plugins-good']
ERROR: Nothing RPROVIDES 'UNRESOLVED-gstreamer1.0-plugins-base' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-play_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-capture_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/sound-play_0.3.3.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-gstreamer1.0-plugins-base' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-gstreamer1.0-plugins-base']
ERROR: Nothing RPROVIDES 'audio-play-dev' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-play_0.3.3.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'audio-play-dev'
NOTE: Runtime target 'audio-play-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['audio-play-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-gstreamer1.0-plugins-ugly' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-play_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/audio-capture_0.3.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/audio-common/sound-play_0.3.3.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-gstreamer1.0-plugins-ugly' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-gstreamer1.0-plugins-ugly']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>