cartographer: work around linking failure with bfd
* when bfd is used, the linking fails with:
  cartographer/1.0.0-r0/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi/../../libexec/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/8.2.0/ld: cartographer/1.0.0-r0/recipe-sysroot/usr/lib/liblua.a(loadlib.o): in function `lsys_sym':
  /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/loadlib.c:134: undefined reference to `dlsym'
  cartographer/1.0.0-r0/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi/../../libexec/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/8.2.0/ld: cartographer/1.0.0-r0/recipe-sysroot/usr/lib/liblua.a(loadlib.o): in function `lsys_load':
  /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/loadlib.c:127: undefined reference to `dlopen'
  cartographer/1.0.0-r0/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi/../../libexec/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/8.2.0/ld: cartographer/1.0.0-r0/recipe-sysroot/usr/lib/liblua.a(loadlib.o): in function `lsys_sym':
  /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/loadlib.c:135: undefined reference to `dlerror'
  cartographer/1.0.0-r0/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi/../../libexec/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/8.2.0/ld: cartographer/1.0.0-r0/recipe-sysroot/usr/lib/liblua.a(loadlib.o): in function `lsys_load':
  /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/loadlib.c:128: undefined reference to `dlerror'
  cartographer/1.0.0-r0/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi/../../libexec/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/8.2.0/ld: cartographer/1.0.0-r0/recipe-sysroot/usr/lib/liblua.a(loadlib.o): in function `lsys_unloadlib':
  /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/loadlib.c:122: undefined reference to `dlclose'
  collect2: error: ld returned 1 exit status

* use gold as a work around (used by default in webOS)