webos-compat.inc: use 4.18 linux-yocto like webOS does
* otherwise 4.14 is used because of:
  conf/ros-distro/include/ubuntu-bionic/ros-distro-platform-preferred-versions.inc:PREFERRED_VERSION_linux-yocto ?= "4.14%"
* and webos-image* builds fail for qemux86 with:
  ERROR: webos-image-ros-turtlebot3-core-1.0-r3 do_rootfs: Unable to install packages. Command '/jenkins/mjansa/build-webos-ose-thud-melodic/BUILD/work/qemux86-webos-linux/webos-image-ros-turtlebot3-core/1.0-r3/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /jenkins/mjansa/build-webos-ose-thud-melodic/BUILD/work/qemux86-webos-linux/webos-image-ros-turtlebot3-core/1.0-r3/opkg.conf -t /jenkins/mjansa/build-webos-ose-thud-melodic/BUILD/work/qemux86-webos-linux/webos-image-ros-turtlebot3-core/1.0-r3/temp/ipktemp/ -o /jenkins/mjansa/build-webos-ose-thud-melodic/BUILD/work/qemux86-webos-linux/webos-image-ros-turtlebot3-core/1.0-r3/rootfs  --force_postinstall --prefer-arch-to-version   install camera-info-manager compressed-image-transport opkg packagegroup-core-boot packagegroup-core-ssh-dropbear packagegroup-webos-extended ros-base rosserial-python run-postinsts tf turtlebot3 turtlebot3-msgs' returned 1:
  Collected errors:
   * Solver encountered 1 problem(s):
   * Problem 1/1:
   *   - nothing provides kernel-module-vboxguest needed by packagegroup-webos-extended-1.0-r30.0.qemux86
   *
   * Solution 1:
   *   - do not ask to install a package providing packagegroup-webos-extended

   * opkg_finalize_intercepts: Failed to open dir /jenkins/mjansa/build-webos-ose-thud-melodic/BUILD/work/qemux86-webos-linux/webos-image-ros-turtlebot3-core/1.0-r3/temp/ipktemp//opkg-BL7CxW/opkg-intercept-Pwgbz0: No such file or directory.
   * rm_r: Failed to open dir /jenkins/mjansa/build-webos-ose-thud-melodic/BUILD/work/qemux86-webos-linux/webos-image-ros-turtlebot3-core/1.0-r3/temp/ipktemp//opkg-BL7CxW/opkg-intercept-Pwgbz0: No such file or directory.
   * rm_r: Failed to open dir /jenkins/mjansa/build-webos-ose-thud-melodic/BUILD/work/qemux86-webos-linux/webos-image-ros-turtlebot3-core/1.0-r3/temp/ipktemp//opkg-BL7CxW: No such file or directory.

Signed-off-by: Martin Jansa <martin.jansa@lge.com>