{eloquent} Fix parsing errors for ros-image-core
ERROR: Nothing RPROVIDES 'UNRESOLVED-python3-ifcfg' (but /jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/ros2cli/ros2doctor_0.8.6-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-python3-ifcfg' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-python3-ifcfg']
NOTE: Runtime target 'ros2doctor' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2doctor', 'UNRESOLVED-python3-ifcfg']
NOTE: Runtime target 'ros-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-core', 'ros2doctor', 'UNRESOLVED-python3-ifcfg']
NOTE: Runtime target 'ros-image-core' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-core', 'ros-core', 'ros2doctor', 'UNRESOLVED-python3-ifcfg']
NOTE: Runtime target 'ros-core-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-core-dev', 'ros2doctor', 'UNRESOLVED-python3-ifcfg']
NOTE: Runtime target 'ros2doctor-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2doctor-dev', 'UNRESOLVED-python3-ifcfg']
ERROR: Nothing RPROVIDES 'UNRESOLVED-python3-cryptography' (but /jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/sros2/sros2_0.8.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-python3-cryptography' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-python3-cryptography']
NOTE: Runtime target 'sros2-cmake' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['sros2-cmake', 'sros2', 'UNRESOLVED-python3-cryptography']
NOTE: Runtime target 'sros2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['sros2', 'UNRESOLVED-python3-cryptography']
NOTE: Runtime target 'sros2-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['sros2-dev', 'UNRESOLVED-python3-cryptography']
ERROR: Nothing RPROVIDES 'sros2-cmake-dev' (but /jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/sros2/sros2-cmake_0.8.1-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'sros2-cmake-dev'
NOTE: Runtime target 'sros2-cmake-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['sros2-cmake-dev']
ERROR: Nothing RPROVIDES 'UNRESOLVED-python3-netifaces' (but /jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/ros2cli/ros2cli_0.8.6-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-python3-netifaces' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2node' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2node', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2lifecycle' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2lifecycle', 'ros2node', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2lifecycle-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2lifecycle-dev', 'ros2node', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2param' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2param', 'ros2node', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2component' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2component', 'ros2param', 'ros2node', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2component-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2component-dev', 'ros2param', 'ros2node', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2param-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2param-dev', 'ros2node', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2node-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2node-dev', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2launch' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2launch', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2launch-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2launch-dev', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2srv' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2srv', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2srv-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2srv-dev', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2service' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2service', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2service-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2service-dev', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2msg' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2msg', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2msg-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2msg-dev', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2topic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2topic', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2topic-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2topic-dev', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2action' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2action', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2action-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2action-dev', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2multicast' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2multicast', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2multicast-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2multicast-dev', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2interface' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2interface', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2interface-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2interface-dev', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2run' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2run', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2run-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2run-dev', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2pkg' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2pkg', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2pkg-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2pkg-dev', 'ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2cli' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2cli', 'UNRESOLVED-python3-netifaces']
NOTE: Runtime target 'ros2cli-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros2cli-dev', 'UNRESOLVED-python3-netifaces']
ERROR: Nothing RPROVIDES 'ament-lint-native' (but virtual:native:/jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/ament-lint/ament-pep257_0.8.1-1.bb, virtual:native:/jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/ament-lint/ament-xmllint_0.8.1-1.bb, virtual:native:/jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/ament-lint/ament-copyright_0.8.1-1.bb, virtual:native:/jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/ament-lint/ament-flake8_0.8.1-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ament-lint-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-lint-native']
NOTE: Runtime target 'ament-cmake-pep257' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-cmake-pep257', 'ament-pep257-native', 'ament-lint-native']
NOTE: Runtime target 'ament-lint-common' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-lint-common', 'ament-cmake-pep257', 'ament-pep257-native', 'ament-lint-native']
NOTE: Runtime target 'ament-lint-common-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-lint-common-dev', 'ament-cmake-pep257', 'ament-pep257-native', 'ament-lint-native']
NOTE: Runtime target 'ament-cmake-pep257-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-cmake-pep257-dev', 'ament-pep257-native', 'ament-lint-native']
NOTE: Runtime target 'ament-cmake-xmllint' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-cmake-xmllint', 'ament-xmllint-native', 'ament-lint-native']
NOTE: Runtime target 'ament-cmake-xmllint-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-cmake-xmllint-dev', 'ament-xmllint-native', 'ament-lint-native']
NOTE: Runtime target 'ament-cmake-copyright' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-cmake-copyright', 'ament-copyright-native', 'ament-lint-native']
NOTE: Runtime target 'ament-cmake-copyright-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-cmake-copyright-dev', 'ament-copyright-native', 'ament-lint-native']
NOTE: Runtime target 'ament-cmake-flake8' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-cmake-flake8', 'ament-flake8-native', 'ament-lint-native']
NOTE: Runtime target 'ament-cmake-flake8-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-cmake-flake8-dev', 'ament-flake8-native', 'ament-lint-native']
ERROR: Nothing PROVIDES 'UNRESOLVED-uncrustify-native' (but virtual:native:/jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/uncrustify-vendor/uncrustify-vendor_1.3.0-1.bb DEPENDS on or otherwise requires it). Close matches:
  ament-uncrustify-native
NOTE: Runtime target 'uncrustify-vendor-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['uncrustify-vendor-native', 'UNRESOLVED-uncrustify-native']
NOTE: Runtime target 'ament-cmake-uncrustify' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-cmake-uncrustify', 'ament-uncrustify-native', 'uncrustify-vendor-native', 'UNRESOLVED-uncrustify-native']
NOTE: Runtime target 'ament-cmake-uncrustify-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ament-cmake-uncrustify-dev', 'ament-uncrustify-native', 'uncrustify-vendor-native', 'UNRESOLVED-uncrustify-native']
ERROR: Nothing RPROVIDES 'UNRESOLVED-uncrustify-native' (but virtual:native:/jenkins/mjansa/build-ros-thud-eloquent/meta-ros/meta-ros2-eloquent/generated-recipes/uncrustify-vendor/uncrustify-vendor_1.3.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'UNRESOLVED-uncrustify-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['UNRESOLVED-uncrustify-native']