{melodic} ros-distro.inc: add mapping for gtk2
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-gtk2' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/image-pipeline/image-view_1.13.0-1.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/webrtc-ros/webrtc_59.0.3.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/stage/stage_4.3.0.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'tuw-marker-detection' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['tuw-marker-detection', 'tuw-checkerboard', 'image-view', 'UNRESOLVED-gtk2']
NOTE: Runtime target 'tuw-checkerboard' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['tuw-checkerboard', 'image-view', 'UNRESOLVED-gtk2']
NOTE: Runtime target 'image-pipeline' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-pipeline', 'image-view', 'UNRESOLVED-gtk2']
NOTE: Runtime target 'perception' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['perception', 'image-pipeline', 'image-view', 'UNRESOLVED-gtk2']
NOTE: Runtime target 'image-view2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-view2', 'image-view', 'UNRESOLVED-gtk2']
NOTE: Runtime target 'image-view' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['image-view', 'UNRESOLVED-gtk2']
NOTE: Runtime target 'webrtc' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['webrtc', 'UNRESOLVED-gtk2']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>