{melodic} packagegroup-ros-world-melodic: remove runtime dependencies on gazebo without ros-gazebo in DISTRO_FEATURES
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-libgazebo9-dev' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/gazebo-ros-pkgs/gazebo-rosdev_2.8.4.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'uuv-gazebo-ros-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['uuv-gazebo-ros-plugins', 'uuv-gazebo-plugins', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'rexrov2-description' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rexrov2-description', 'uuv-gazebo-ros-plugins', 'uuv-gazebo-plugins', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'rexrov2-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rexrov2-gazebo', 'rexrov2-description', 'uuv-gazebo-ros-plugins', 'uuv-gazebo-plugins', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'eca-a9-description' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['eca-a9-description', 'uuv-gazebo-ros-plugins', 'uuv-gazebo-plugins', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'eca-a9-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['eca-a9-gazebo', 'eca-a9-description', 'uuv-gazebo-ros-plugins', 'uuv-gazebo-plugins', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'lauv-description' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lauv-description', 'uuv-gazebo-ros-plugins', 'uuv-gazebo-plugins', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'lauv-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lauv-gazebo', 'lauv-description', 'uuv-gazebo-ros-plugins', 'uuv-gazebo-plugins', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'lauv-control' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lauv-control', 'lauv-description', 'uuv-gazebo-ros-plugins', 'uuv-gazebo-plugins', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'desistek-saga-description' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['desistek-saga-description', 'uuv-gazebo-ros-plugins', 'uuv-gazebo-plugins', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'desistek-saga-control' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['desistek-saga-control', 'desistek-saga-description', 'uuv-gazebo-ros-plugins', 'uuv-gazebo-plugins', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'desistek-saga-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['desistek-saga-gazebo', 'desistek-saga-control', 'desistek-saga-description', 'uuv-gazebo-ros-plugins', 'uuv-gazebo-plugins', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'uuv-descriptions' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['uuv-descriptions', 'uuv-gazebo-ros-plugins', 'uuv-gazebo-plugins', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'uuv-simulator' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['uuv-simulator', 'uuv-descriptions', 'uuv-gazebo-ros-plugins', 'uuv-gazebo-plugins', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'uuv-sensor-ros-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['uuv-sensor-ros-plugins', 'uuv-gazebo-plugins', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'uuv-gazebo-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['uuv-gazebo-plugins', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'fetch-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fetch-gazebo', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'fetchit-challenge' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fetchit-challenge', 'fetch-gazebo', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'open-manipulator-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['open-manipulator-gazebo', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'open-manipulator-simulations' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['open-manipulator-simulations', 'open-manipulator-gazebo', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'audibot-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['audibot-gazebo', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'audibot' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['audibot', 'audibot-gazebo', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'turtlebot3-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-gazebo', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'turtlebot3-simulations' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['turtlebot3-simulations', 'turtlebot3-gazebo', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'open-manipulator-with-tb3-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['open-manipulator-with-tb3-gazebo', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'open-manipulator-with-tb3-simulations' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['open-manipulator-with-tb3-simulations', 'open-manipulator-with-tb3-gazebo', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'uuv-gazebo-worlds' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['uuv-gazebo-worlds', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'urdf-sim-tutorial' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['urdf-sim-tutorial', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'ainstein-radar-gazebo-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ainstein-radar-gazebo-plugins', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'velodyne-gazebo-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['velodyne-gazebo-plugins', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'velodyne-simulator' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['velodyne-simulator', 'velodyne-gazebo-plugins', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'igvc-self-drive-gazebo-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['igvc-self-drive-gazebo-plugins', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'igvc-self-drive-sim' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['igvc-self-drive-sim', 'igvc-self-drive-gazebo-plugins', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'usv-gazebo-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['usv-gazebo-plugins', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'wave-gazebo-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['wave-gazebo-plugins', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'cob-gazebo-ros-control' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-gazebo-ros-control', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'cob-gazebo-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-gazebo-plugins', 'cob-gazebo-ros-control', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'jackal-simulator' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['jackal-simulator', 'jackal-gazebo', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'warthog-simulator' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['warthog-simulator', 'warthog-gazebo', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'ridgeback-simulator' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ridgeback-simulator', 'ridgeback-gazebo', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'gazebo-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'raw-description' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['raw-description', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'cob-hardware-config' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-hardware-config', 'raw-description', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'cob-common' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-common', 'raw-description', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'cob-gazebo-objects' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-gazebo-objects', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'igvc-self-drive-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['igvc-self-drive-gazebo', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'cob-description' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-description', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'cob-grasp-generation' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-grasp-generation', 'cob-description', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'blender-gazebo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['blender-gazebo', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'cob-gazebo-worlds' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-gazebo-worlds', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'yosemite-valley' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['yosemite-valley', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'rexrov2-control' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rexrov2-control', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'ksql-airport' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ksql-airport', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'mcmillan-airfield' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mcmillan-airfield', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'sand-island' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['sand-island', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'gazebo-ros-control' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros-control', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'mir-description' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mir-description', 'gazebo-ros-control', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'gazebo-ros-pkgs' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-ros-pkgs', 'gazebo-ros', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'uuv-world-ros-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['uuv-world-ros-plugins', 'uuv-world-plugins', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'uuv-world-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['uuv-world-plugins', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'gazebo-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-plugins', 'gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']
NOTE: Runtime target 'gazebo-rosdev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gazebo-rosdev', 'UNRESOLVED-libgazebo9-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>