SQUASH? webos-image-ros-turtlebot3-*: fix parsing errors without meta-webos
* fixes:
  Parsing recipes...
  ERROR: meta-ros/meta-ros-common/recipes-core/images/webos-image-ros-turtlebot3-all.bb: This recipe does not have the LICENSE field set (webos-image-ros-turtlebot3-all)
  ERROR: meta-ros/meta-ros-common/recipes-core/images/webos-image-ros-turtlebot3-core.bb: This recipe does not have the LICENSE field set (webos-image-ros-turtlebot3-core)

* need to set LICENSE variable, because the error above is shown before
  PNBLACKLIST is processed.

* also cannot use require instead of include, because that would cause parsing
  failure, before PNBLACKLIST skips the recipe:
  ERROR: ParseError at meta-ros-common/recipes-core/images/webos-image-ros-turtlebot3-core.bb:5:
  Could not include required file /recipes-core/images/webos-image.bb

Signed-off-by: Martin Jansa <martin.jansa@lge.com>