{dashing} ompl: backport a fix for build with boost-1.71
* fixes:
In file included from ompl/1.4.2-2-r0/git/demos/PlannerData.cpp:45:
ompl/1.4.2-2-r0/recipe-sysroot/usr/include/boost/graph/astar_search.hpp: In instantiation of 'void boost::astar_search(const VertexListGraph&, typename boost::graph_traits<Graph>::vertex_descriptor, AStarHeuristic, const boost::bgl_named_params<P, T, R>&) [with VertexListGraph = boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, boost::property<vertex_type_t, ompl::base::PlannerDataVertex*, boost::property<boost::vertex_index_t, unsigned int> >, boost::property<edge_type_t, ompl::base::PlannerDataEdge*, boost::property<boost::edge_weight_t, ompl::base::Cost> > >; AStarHeuristic = readPlannerData()::<lambda(ompl::base::PlannerData::Graph::Vertex)>; P = ompl::base::Cost; T = boost::distance_zero_t; R = boost::bgl_named_params<ompl::base::Cost, boost::distance_inf_t, boost::bgl_named_params<readPlannerData()::<lambda(ompl::base::Cost, ompl::base::Cost)>, boost::distance_combine_t, boost::bgl_named_params<readPlannerData()::<lambda(ompl::base::Cost, ompl::base::Cost)>, boost::distance_compare_t, boost::bgl_named_params<boost::vector_property_map<unsigned int>, boost::vertex_predecessor_t, boost::no_property> > > >; typename boost::graph_traits<Graph>::vertex_descriptor = unsigned int]':
ompl/1.4.2-2-r0/git/demos/PlannerData.cpp:179:46:   required from here
ompl/1.4.2-2-r0/recipe-sysroot/usr/include/boost/graph/astar_search.hpp:449:13: error: invalid initialization of reference of type 'boost::parameter::binding<boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<boost::graph::keywords::tag::distance_zero, const ompl::base::Cost>, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<boost::graph::keywords::tag::distance_inf, const ompl::base::Cost>, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<boost::graph::keywords::tag::distance_combine, const readPlannerData()::<lambda(ompl::base::Cost, ompl::base::Cost)> >, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<boost::graph::keywords::tag::distance_compare, const readPlannerData()::<lambda(ompl::base::Cost, ompl::base::Cost)> >, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<boost::graph::keywords::tag::predecessor_map, const boost::vector_property_map<unsigned int> >, boost::parameter::aux::empty_arg_list, std::integral_constant<bool, true> >, std::integral_constant<bool, true> >, std::integral_constant<bool, true> >, std::integral_constant<bool, true> >, std::integral_constant<bool, true> >, boost::graph::keywords::tag::visitor, boost::dummy_property_map&>::type' {aka 'boost::dummy_property_map&'} from expression of type 'boost::astar_visitor<>'
  449 |     >::type vis = arg_pack[_visitor | default_visitor];
      |             ^~~
ompl/1.4.2-2-r0/recipe-sysroot/usr/include/boost/graph/astar_search.hpp: At global scope:
ompl/1.4.2-2-r0/recipe-sysroot/usr/include/boost/graph/astar_search.hpp:353:3: error: 'void boost::astar_search(const VertexListGraph&, typename boost::graph_traits<Graph>::vertex_descriptor, AStarHeuristic, AStarVisitor, PredecessorMap, CostMap, DistanceMap, WeightMap, VertexIndexMap, ColorMap, CompareFunction, CombineFunction, CostInf, CostZero) [with VertexListGraph = boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, boost::property<vertex_type_t, ompl::base::PlannerDataVertex*, boost::property<boost::vertex_index_t, unsigned int> >, boost::property<edge_type_t, ompl::base::PlannerDataEdge*, boost::property<boost::edge_weight_t, ompl::base::Cost> > >; AStarHeuristic = readPlannerData()::<lambda(ompl::base::PlannerData::Graph::Vertex)>; AStarVisitor = boost::dummy_property_map; PredecessorMap = boost::vector_property_map<unsigned int>; CostMap = boost::shared_array_property_map<ompl::base::Cost, boost::vec_adj_list_vertex_id_map<boost::property<vertex_type_t, ompl::base::PlannerDataVertex*, boost::property<boost::vertex_index_t, unsigned int> >, unsigned int> >; DistanceMap = boost::shared_array_property_map<ompl::base::Cost, boost::vec_adj_list_vertex_id_map<boost::property<vertex_type_t, ompl::base::PlannerDataVertex*, boost::property<boost::vertex_index_t, unsigned int> >, unsigned int> >; WeightMap = boost::adj_list_edge_property_map<boost::bidirectional_tag, ompl::base::Cost, const ompl::base::Cost&, unsigned int, const boost::property<edge_type_t, ompl::base::PlannerDataEdge*, boost::property<boost::edge_weight_t, ompl::base::Cost> >, boost::edge_weight_t>; VertexIndexMap = boost::vec_adj_list_vertex_id_map<boost::property<vertex_type_t, ompl::base::PlannerDataVertex*, boost::property<boost::vertex_index_t, unsigned int> >, unsigned int>; ColorMap = boost::shared_array_property_map<boost::default_color_type, boost::vec_adj_list_vertex_id_map<boost::property<vertex_type_t, ompl::base::PlannerDataVertex*, boost::property<boost::vertex_index_t, unsigned int> >, unsigned int> >; CompareFunction = readPlannerData()::<lambda(ompl::base::Cost, ompl::base::Cost)>; CombineFunction = readPlannerData()::<lambda(ompl::base::Cost, ompl::base::Cost)>; CostInf = ompl::base::Cost; CostZero = ompl::base::Cost; typename boost::graph_traits<Graph>::vertex_descriptor = unsigned int]', declared using local type 'readPlannerData()::<lambda(ompl::base::PlannerData::Graph::Vertex)>', is used but never defined [-fpermissive]
  353 |   astar_search
      |   ^~~~~~~~~~~~

Signed-off-by: Martin Jansa <martin.jansa@lge.com>