webos-compat.inc: make sure that RPI_KERNEL_DEVICETREE_3BPLUS is defined
* otherwise build for raspberrypi4 fails with:
  WARNING: meta-raspberrypi/recipes-core/images/rpi-hwup-image.bb:
  Exception during build_dependencies for IMAGE_BOOT_FILES
  WARNING: meta-raspberrypi/recipes-core/images/rpi-hwup-image.bb:

  Error during finalise of meta-raspberrypi/recipes-core/images/rpi-hwup-image.bb

  ERROR: ExpansionError during parsing meta-webos-ros/recipes-core/images/webos-image-ros-core.bb
  Traceback (most recent call last):
  bb.data_smart.ExpansionError: Failure expanding variable IMAGE_BOOT_FILES, expression was bcm2835-bootfiles/*                  ${@make_dtb_boot_files(d)}                  ${@bb.utils.contains('RPI_USE_U_BOOT', '1',                     'uImage u-boot.bin;kernel7l.img boot.scr',                     'uImage;kernel7l.img', d)}                   which triggered exception TypeError: sequence item 9: expected str instance, NoneType found

  because there is unexpanded ${RPI_KERNEL_DEVICETREE_3BPLUS} in
  RPI_KERNEL_DEVICETREE which breaks the make_dtb_boot_files function
  called in IMAGE_BOOT_FILES

  RPI_KERNEL_DEVICETREE="     bcm2708-rpi-zero-w.dtb     bcm2708-rpi-b.dtb
  bcm2708-rpi-b-plus.dtb     bcm2709-rpi-2-b.dtb     bcm2710-rpi-3-b.dtb
  bcm2710-rpi-3-b-plus.dtb     bcm2711-rpi-4-b.dtb     bcm2708-rpi-cm.dtb
  bcm2710-rpi-cm3.dtb          \${RPI_KERNEL_DEVICETREE_3BPLUS} "

Signed-off-by: Martin Jansa <martin.jansa@lge.com>